name: Determine Marketplace Identity

on:
  workflow_dispatch:
  push:

jobs:
  identity:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: vscode-marketplace
    steps:
      - name: Azure login (user-assigned managed identity)
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Determine Marketplace Identity
        run: |
          az rest \
            -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me \
            --resource 499b84ac-1321-427f-aa17-267ca6975798
